NDefines.NCountry.PS_BOOST_STABILITY = 10000
NDefines.NCountry.PS_REDUCE_INFLATION = 7500
NDefines.NCountry.PS_REDUCE_WAREXHAUSTION = 7500
NDefines.NCountry.PS_STRENGTHEN_GOVERNMENT = 10000

NDefines.NCountry.ESTATE_ANGRY_THRESHOLD = 40

NDefines.NAI.ESTATE_MAX_PRIVILEDGES = 4